/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;
import com.mycompany.carservice.entity.CSVHandler;
import com.mycompany.carservice.entity.RoundedPanel;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author usEr
 */
public class PopResetPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PopResetPassword.class.getName());
    private final String user;
    private final String email;
    private final String phonenumber;
    

    /**
     * Creates new form PopConfirm
     */
    public PopResetPassword(String user, String email, String phonenumber) {
        initComponents();
        setSize(415, 335);
        setLocationRelativeTo(null);
        setVisible(true);
        this.user = user;
        this.email = email;
        this.phonenumber = phonenumber;
        cautionpass.setHorizontalTextPosition(JLabel.RIGHT); // ข้อความอยู่ซ้าย, icon อยู่ขวา
        cautionconfirmpass.setHorizontalTextPosition(JLabel.RIGHT);
        cautionpass.setVisible(false); 
        cautionconfirmpass.setVisible(false); 
    }
    
    private void saveNewPassword(String newPassword) {
                if(newPassword == null || newPassword.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter a password");
                    return;
                }

                CSVHandler csvHandler = new CSVHandler("src/main/data/user.csv");
                ArrayList<String[]> users = csvHandler.readCSV();
                boolean updated = false;

                for (String[] parts : users) {
                    if (parts.length >= 6) {
                        if (parts[1].equals(user) && parts[3].equals(email) && parts[4].equals(phonenumber)) {
                            parts[2] = newPassword;
                            updated = true;
                            break;
                        }
                    }
                }

                if (updated) {
                    csvHandler.writeCSV(users);
                    JOptionPane.showMessageDialog(this, "Password updated successfully!");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "User not found!");
                }
        }
    private void checkPassword(){
            String pass = new String(password.getPassword()).trim();
            String confirmpass = new String(confirmPassword.getPassword()).trim(); 
            int sumpass = 0;
            int sumconfirm = 0;
            
            if (pass.isEmpty()) {
                cautionpass.setText("Need to input password");
                cautionpass.setVisible(true);
                sumpass=1;
            }else if (pass.length() < 6) {
                cautionpass.setText("Password need at least 6 characters");
                cautionpass.setVisible(true);
                sumpass=1;
            }else if (!pass.matches(".*\\d.*")) {
                cautionpass.setText("Password must have number");
                cautionpass.setVisible(true);
                sumpass=1;
            }else if (!pass.matches(".*[a-z].*")) {
                cautionpass.setText("Password must have lowercase letter");
                cautionpass.setVisible(true);
                sumpass=1;
            }else if (!pass.matches(".*[A-Z].*")) {
                cautionpass.setText("Password must have uppercase letter");
                cautionpass.setVisible(true);
                sumpass=1;
            }else if (!pass.matches(".*[!@#$%^&*()].*")) {
                cautionpass.setText("Password must have special character");
                cautionpass.setVisible(true);
                sumpass=1;
            }else{
                cautionpass.setText("");
                cautionpass.setVisible(false);
                sumpass=0;
            }
            
            if (confirmpass.isEmpty()) {
                cautionconfirmpass.setText("Need to confirm password");
                cautionconfirmpass.setVisible(true);
                sumconfirm=1;
            }else if (!confirmpass.equals(pass)) {
                cautionconfirmpass.setText("Nah");
                cautionconfirmpass.setVisible(true);
                sumpass=1;
            }else{
                cautionconfirmpass.setText("");
                cautionconfirmpass.setVisible(false);
                sumconfirm=0;
            }
            
            if(sumpass == 0 && sumconfirm == 0){
                saveNewPassword(pass);
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(30); // 30 radius;
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cautionpass = new javax.swing.JLabel();
        cautionconfirmpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(43, 43, 43));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        cancel.setText("Back");
        cancel.setToolTipText("");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 20));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, 30));

        confirmPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 30));

        jLabel3.setText("Confirm Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 20));

        cautionpass.setForeground(new java.awt.Color(255, 51, 51));
        cautionpass.setText("...");
        jPanel3.add(cautionpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, -1));

        cautionconfirmpass.setForeground(new java.awt.Color(255, 0, 0));
        cautionconfirmpass.setText("...");
        jPanel3.add(cautionconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 360, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        checkPassword();
    }//GEN-LAST:event_saveMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dispose();
        new PopConfirm();
    }//GEN-LAST:event_cancelMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cautionconfirmpass;
    private javax.swing.JLabel cautionpass;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
