/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import com.mycompany.carservice.entity.CSVHandler;

import java.util.ArrayList;
import java.util.List;
import com.mycompany.carservice.gui.*;
/**
 *
 * @author fame
 */
public class Changepassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Changepassword.class.getName());
    private String userName;
    private String role;
   // private Profile profileFrame;
    
    public Changepassword(String userName,String role) {
        initComponents();
        setSize(500, 452);  
        setLocationRelativeTo(null);
        setVisible(true);
        this.userName = userName;
        this.role = role;
    }
    private String validatePassword(String password) {
         boolean hasUpper = false, hasDigit = false, hasSpecial = false;

    for (char c : password.toCharArray()) {
        if (Character.isUpperCase(c)) hasUpper = true;
        else if (Character.isDigit(c)) hasDigit = true;
        else if (!Character.isLetterOrDigit(c)) hasSpecial = true;
    }

    StringBuilder error = new StringBuilder();  // เก็บข้อความ error
    if (!hasUpper) error.append("- ต้องมีตัวอักษรพิมพ์ใหญ่ 1 ตัว\n");
    if (!hasDigit) error.append("- ต้องมีตัวเลข 1 ตัว\n");
    if (!hasSpecial) error.append("- ต้องมีตัวอักษรพิเศษ 1 ตัว\n");
    return error.toString(); // คืนค่าข้อความ error
}
    
    
    private void updatePassword(String oldPass, String newPass) {
    CSVHandler csvHandler = new CSVHandler("src/main/data/user.csv");
    ArrayList<String[]> users = csvHandler.readCSV();

    for (int i = 1; i < users.size(); i++) {
        String[] row = users.get(i); // ดึงข้อมูลผู้ใช้แถวปัจจุบัน
        if (row[1].equals(userName)) { // ตรวจสอบ username ตรงกับผู้ใช้
            if (!row[2].equals(oldPass)) { // ตรวจสอบรหัสเก่า
                JOptionPane.showMessageDialog(this, "รหัสเก่าไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE);
                return;// ออกจากฟังก์ชัน
            }

            String error = validatePassword(newPass); // ตรวจสอบรหัสใหม่
            if (!error.isEmpty()) { 
                JOptionPane.showMessageDialog(this, "รหัสผ่านไม่ถูกต้อง:\n" + error, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // อัปเดตรหัสผ่าน
            row[2] = newPass;
            users.set(i, row);
            csvHandler.writeCSV(users);

            JOptionPane.showMessageDialog(this, "เปลี่ยนรหัสผ่านสำเร็จ", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Profile(userName, role);
            return;
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        oldpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newpassword = new javax.swing.JTextField();
        confrimpassword = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(43, 43, 43));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profile");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(458, 237));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("old password ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        oldpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(oldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 290, 40));

        jLabel3.setText("new password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("confrim password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel3.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 40));

        confrimpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(confrimpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 290, 40));

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 280));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasswordActionPerformed

    private void confrimpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confrimpasswordActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        
    }//GEN-LAST:event_backMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
      String oldPass = oldpassword.getText().trim();
    String newPass = newpassword.getText().trim();
    String confirmPass = confrimpassword.getText().trim();

    if (oldPass.isEmpty() || newPass.isEmpty() || confirmPass.isEmpty()) { // กรอกไม่ครบ
        JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ครบ", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!newPass.equals(confirmPass)) { // รหัสใหม่ไม่ตรงกับยืนยันรหัส
        JOptionPane.showMessageDialog(this, "รหัสใหม่และยืนยันรหัสไม่ตรงกัน", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    updatePassword(oldPass, newPass);  // อัปเดตรหัสผ่าน
    }//GEN-LAST:event_saveMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField confrimpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField newpassword;
    private javax.swing.JTextField oldpassword;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
