/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;


/**
 *
 * @author User
 */
public class History extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(History.class.getName());
  
    
    
    /**
     * Creates new form History
     */
    public History() {
        
        initComponents();
        setupUi();
        setSize(1210, 800);  
        setLocationRelativeTo(null); // จัดตรงกลางจอ
        setVisible(true);
    }
    private void setupUi(){
       homebutton.setBorderPainted(false);
       bookingbutton.setBorderPainted(false);
       historybutton.setBorderPainted(false);
       profilebutton.setBorderPainted(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        textMain = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        textBooking = new javax.swing.JLabel();
        bookingbutton = new javax.swing.JButton();
        testHistory = new javax.swing.JLabel();
        historybutton = new javax.swing.JButton();
        textProfile = new javax.swing.JLabel();
        profilebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2149, 0, -1, 207));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 58, 58));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USER :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 36, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 35, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nannapat");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 37, 130, 30));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 35, -1, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        jPanel3.setBackground(new java.awt.Color(28, 24, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 744, -1, 1137));

        jPanel8.setBackground(new java.awt.Color(28, 24, 24));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textMain.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        textMain.setForeground(new java.awt.Color(255, 255, 255));
        textMain.setText("Home");
        textMain.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textMainAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMainMouseClicked(evt);
            }
        });
        jPanel8.add(textMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        homebutton.setBackground(new java.awt.Color(28, 24, 24));
        homebutton.setPreferredSize(new java.awt.Dimension(101, 43));
        homebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebuttonMouseClicked(evt);
            }
        });
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 164, 90));

        textBooking.setBackground(new java.awt.Color(28, 24, 24));
        textBooking.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        textBooking.setForeground(new java.awt.Color(255, 255, 255));
        textBooking.setText("Booking");
        textBooking.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textBookingAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBookingMouseClicked(evt);
            }
        });
        jPanel8.add(textBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        bookingbutton.setBackground(new java.awt.Color(28, 24, 24));
        bookingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingbuttonMouseClicked(evt);
            }
        });
        bookingbutton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                bookingbuttonComponentHidden(evt);
            }
        });
        jPanel8.add(bookingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 164, 90));

        testHistory.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        testHistory.setText("History");
        testHistory.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                testHistoryAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        testHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testHistoryMouseClicked(evt);
            }
        });
        jPanel8.add(testHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        historybutton.setBackground(new java.awt.Color(255, 153, 0));
        historybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historybuttonMouseClicked(evt);
            }
        });
        historybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybuttonActionPerformed(evt);
            }
        });
        jPanel8.add(historybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 164, 90));

        textProfile.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        textProfile.setForeground(new java.awt.Color(255, 255, 255));
        textProfile.setText("Profile");
        textProfile.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textProfileAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textProfileMouseClicked(evt);
            }
        });
        jPanel8.add(textProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        profilebutton.setBackground(new java.awt.Color(28, 24, 24));
        profilebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilebuttonMouseClicked(evt);
            }
        });
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 164, 90));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 800));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "go", "mail.com", "000"},
                {"2", "po", "mail.com", "999"},
                {"3", "yo", "mail.com", "888"},
                {"4", "ro", "mail.com", "777"}
            },
            new String [] {
                "No", "User", "gmail", "Tell"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 950, 550));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Load");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 690, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 690, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textProfileMouseClicked

    private void textProfileAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textProfileAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textProfileAncestorAdded

    private void testHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_testHistoryMouseClicked

    private void testHistoryAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_testHistoryAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_testHistoryAncestorAdded

    private void textBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBookingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textBookingMouseClicked

    private void textBookingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textBookingAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textBookingAncestorAdded

    private void textMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textMainMouseClicked

    private void textMainAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textMainAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textMainAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           model.addRow(new Object[]{"1", "go", "mail.com", "000"});
           model.addRow(new Object[]{"2", "po", "mail.com", "999"});
           model.addRow(new Object[]{"3", "yo", "mail.com", "888"});
           model.addRow(new Object[]{"4", "ro", "mail.com", "777"});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homebuttonActionPerformed

    private void homebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homebuttonMouseClicked

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilebuttonActionPerformed

    private void profilebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilebuttonMouseClicked

    private void historybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historybuttonActionPerformed

    private void historybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_historybuttonMouseClicked

    private void bookingbuttonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bookingbuttonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbuttonComponentHidden

    private void bookingbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbuttonMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new History().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingbutton;
    private javax.swing.JButton historybutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton profilebutton;
    private javax.swing.JLabel testHistory;
    private javax.swing.JLabel textBooking;
    private javax.swing.JLabel textMain;
    private javax.swing.JLabel textProfile;
    // End of variables declaration//GEN-END:variables
}
