/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;
import java.awt.Color;
import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;




/**
 *
 * @author User
 */
public class History extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(History.class.getName());
    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        setupUi();
        loadHistoryData();
         //จัดข้อความให้อยู่ตรงกลาง
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
         // จัดกลางข้อมูลทุกคอลัมน์
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        setSize(1210, 810);  
        setLocationRelativeTo(null); // จัดตรงกลางจอ
        setVisible(true);
        jTable1.setRowHeight(50);
    }
    private void setupUi(){
       UIManager.put("Table.selectionBackground", new Color(0, 0, 0));
       UIManager.put("Table.selectionForeground", Color.WHITE);
       UIManager.put("Table.alternateRowColor", Color.GRAY);
       homebutton.setBorderPainted(false);
       bookingbutton.setBorderPainted(false);
       historybutton.setBorderPainted(false);
       profilebutton.setBorderPainted(false);
       

    }
  private void loadHistoryData() {
    String filePath = "src/main/data/history_user.csv";
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String currentUser = jLabel1.getText().trim();  // ชื่อผู้ใช้ปัจจุบัน
    int rowNumber = 1;

    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        boolean firstLine = true;

        while ((line = br.readLine()) != null) {
            if (firstLine) { // ข้าม header
                firstLine = false;
                continue;
            }

            String[] data = line.split(",");

            if (data.length >= 8) {
                String nameInCsv = data[1].replace("\uFEFF", "").trim(); // ใช้ column 1 = Name

                System.out.println("CSV Name: [" + nameInCsv + "]");
                System.out.println("Current User: [" + currentUser + "]");

                if (nameInCsv.equalsIgnoreCase(currentUser)) {
                    Object[] newRow = {
                    rowNumber,        // No (ลำดับในตาราง)
                    nameInCsv,        // Name
                    data[2].trim(),   // Service
                    data[3].trim(),   // Date
                    data[4].trim(),   // Time
                    data[5].trim(),   // Note
                    data[6].trim(),   // Car registration
                    data[7].trim()    // Status
            };
                    model.addRow(newRow);
                    rowNumber++;
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading history data");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Booking = new javax.swing.JLabel();
        History = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        textMain = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        textBooking = new javax.swing.JLabel();
        bookingbutton = new javax.swing.JButton();
        testHistory = new javax.swing.JLabel();
        historybutton = new javax.swing.JButton();
        textProfile = new javax.swing.JLabel();
        profilebutton = new javax.swing.JButton();
        logoCarConnect = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        UserName = new javax.swing.JLabel();
        profileuser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2149, 0, -1, 207));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 24, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 744, -1, 1137));

        jPanel8.setBackground(new java.awt.Color(28, 24, 24));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Booking.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\booking.png")); // NOI18N
        Booking.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel8.add(Booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 21));

        History.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\history.png")); // NOI18N
        History.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel8.add(History, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\home.png")); // NOI18N
        Home.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel8.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        Profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\profile.png")); // NOI18N
        jPanel8.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        textMain.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textMain.setForeground(new java.awt.Color(255, 255, 255));
        textMain.setText("Home");
        textMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textMain.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textMainAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMainMouseClicked(evt);
            }
        });
        jPanel8.add(textMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        homebutton.setBackground(new java.awt.Color(28, 24, 24));
        homebutton.setPreferredSize(new java.awt.Dimension(101, 43));
        homebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebuttonMouseExited(evt);
            }
        });
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 206, 60));

        textBooking.setBackground(new java.awt.Color(28, 24, 24));
        textBooking.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textBooking.setForeground(new java.awt.Color(255, 255, 255));
        textBooking.setText("Booking");
        textBooking.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textBookingAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBookingMouseClicked(evt);
            }
        });
        jPanel8.add(textBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        bookingbutton.setBackground(new java.awt.Color(28, 24, 24));
        bookingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingbuttonMouseExited(evt);
            }
        });
        bookingbutton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                bookingbuttonComponentHidden(evt);
            }
        });
        bookingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingbuttonActionPerformed(evt);
            }
        });
        jPanel8.add(bookingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 206, 60));

        testHistory.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        testHistory.setText("History");
        testHistory.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                testHistoryAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        testHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testHistoryMouseClicked(evt);
            }
        });
        jPanel8.add(testHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        historybutton.setBackground(new java.awt.Color(255, 153, 0));
        historybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historybuttonMouseClicked(evt);
            }
        });
        historybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybuttonActionPerformed(evt);
            }
        });
        jPanel8.add(historybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 206, 60));

        textProfile.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textProfile.setForeground(new java.awt.Color(255, 255, 255));
        textProfile.setText("Profile");
        textProfile.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textProfileAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textProfileMouseClicked(evt);
            }
        });
        jPanel8.add(textProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        profilebutton.setBackground(new java.awt.Color(28, 24, 24));
        profilebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilebuttonMouseExited(evt);
            }
        });
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });
        jPanel8.add(profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 206, 60));

        logoCarConnect.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\logoCarConnect.png")); // NOI18N
        jPanel8.add(logoCarConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 133));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 240, 800));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "Service", "Date", "Time", "Note", "Car registration", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 930, 690));

        UserName.setBackground(new java.awt.Color(255, 255, 255));
        UserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserName.setText("USER :");
        jPanel7.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        profileuser.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\profileuser.png")); // NOI18N
        jPanel7.add(profileuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("สมหญิง รุ่งเรือง");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 140, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textProfileMouseClicked

    private void textProfileAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textProfileAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textProfileAncestorAdded

    private void testHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_testHistoryMouseClicked

    private void testHistoryAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_testHistoryAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_testHistoryAncestorAdded

    private void textBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBookingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textBookingMouseClicked

    private void textBookingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textBookingAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textBookingAncestorAdded

    private void textMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textMainMouseClicked

    private void textMainAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textMainAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textMainAncestorAdded

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
      
    }//GEN-LAST:event_homebuttonActionPerformed

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilebuttonActionPerformed

    private void historybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historybuttonActionPerformed

    private void historybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_historybuttonMouseClicked

    private void bookingbuttonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bookingbuttonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbuttonComponentHidden

    private void homebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseEntered
       homebutton.setBackground(Color.GRAY);
       homebutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_homebuttonMouseEntered

    private void homebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseExited
        homebutton.setBackground(new Color(28,24,24));
        homebutton.setForeground(Color.BLACK);
    }//GEN-LAST:event_homebuttonMouseExited

    private void bookingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbuttonActionPerformed

    private void bookingbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingbuttonMouseEntered
       bookingbutton.setBackground(Color.GRAY);
       bookingbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_bookingbuttonMouseEntered

    private void bookingbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingbuttonMouseExited
        bookingbutton.setBackground(new Color(28,24,24));
        bookingbutton.setForeground(Color.BLACK);
    }//GEN-LAST:event_bookingbuttonMouseExited

    private void profilebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebuttonMouseEntered
        profilebutton.setBackground(Color.GRAY);
        profilebutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_profilebuttonMouseEntered

    private void profilebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebuttonMouseExited
        profilebutton.setBackground(new Color(28,24,24));
        profilebutton.setForeground(Color.BLACK);
    }//GEN-LAST:event_profilebuttonMouseExited
 
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Booking;
    private javax.swing.JLabel History;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton bookingbutton;
    private javax.swing.JButton historybutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoCarConnect;
    private javax.swing.JButton profilebutton;
    private javax.swing.JLabel profileuser;
    private javax.swing.JLabel testHistory;
    private javax.swing.JLabel textBooking;
    private javax.swing.JLabel textMain;
    private javax.swing.JLabel textProfile;
    // End of variables declaration//GEN-END:variables
}
