/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;


import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import java.io.File;
import java.net.*;
import javax.swing.*;
import java.net.URL;
import java.io.*;


/**
 *
 * @author usEr
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
            setupComponent();
            initComponents();
            setSize(1200, 800);  
            setLocationRelativeTo(null);
            setVisible(true);
            cautionusername.setVisible(false);cautionpass.setVisible(false);
//            iconusername.setIcon(new ImageIcon(getClass().getResource("src/main/image/user.png")));
//            iconpassword.setIcon(new ImageIcon(getClass().getResource("src/main/image/padlock.png")));
            try {
                URL userIconURL = new File("src/main/image/user.png").toURI().toURL();
                URL passIconURL = new File("src/main/image/padlock.png").toURI().toURL();
                iconusername.setIcon(new ImageIcon(userIconURL));
                iconpassword.setIcon(new ImageIcon(passIconURL));
            } catch (MalformedURLException e) {
                e.printStackTrace();
                logger.severe("Cannot load icon images");
            }
            
    }
    private void setupComponent(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        iconusername = new javax.swing.JLabel();
        iconpassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        anotherRegister = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cautionusername = new javax.swing.JLabel();
        cautionpass = new javax.swing.JLabel();
        loginFinish = new javax.swing.JButton();
        username = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(58, 58, 58));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jLabel2.setToolTipText("");

        logButton.setBackground(new java.awt.Color(255, 149, 0));
        logButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        logButton.setText("Login");
        logButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logButtonMouseExited(evt);
            }
        });
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 368, 800));
        jPanel3.add(iconusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 50, 60));
        jPanel3.add(iconpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 50, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 135, -1, 62));

        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password.setMargin(new java.awt.Insets(2, 55, 2, 6));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 530, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 238, -1, -1));

        anotherRegister.setForeground(new java.awt.Color(255, 255, 255));
        anotherRegister.setText("have an account? Register");
        anotherRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anotherRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anotherRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anotherRegisterMouseExited(evt);
            }
        });
        jPanel3.add(anotherRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 346, -1, -1));

        cautionusername.setForeground(new java.awt.Color(255, 0, 51));
        cautionusername.setText("can't use this password it's less than 8 charactor");
        cautionusername.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(cautionusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        cautionpass.setForeground(new java.awt.Color(255, 0, 51));
        cautionpass.setText("can't use this password it's less than 8 charactor");
        cautionpass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(cautionpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        loginFinish.setBackground(new java.awt.Color(255, 149, 0));
        loginFinish.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        loginFinish.setText("Login");
        loginFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginFinishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginFinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginFinishMouseExited(evt);
            }
        });
        loginFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFinishActionPerformed(evt);
            }
        });
        jPanel3.add(loginFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 530, 60));

        username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username.setMargin(new java.awt.Insets(2, 55, 2, 6));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 530, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void anotherRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotherRegisterMouseClicked
        dispose();
        new Register();
    }//GEN-LAST:event_anotherRegisterMouseClicked

    private void anotherRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotherRegisterMouseEntered
        anotherRegister.setForeground(Color.GRAY);
    }//GEN-LAST:event_anotherRegisterMouseEntered

    private void anotherRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotherRegisterMouseExited
        anotherRegister.setForeground(Color.WHITE);
    }//GEN-LAST:event_anotherRegisterMouseExited

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        
    }//GEN-LAST:event_passwordKeyTyped

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logButtonActionPerformed

    private void logButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseClicked
        dispose();
        new Login();
    }//GEN-LAST:event_logButtonMouseClicked

    private void logButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseEntered
        logButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_logButtonMouseEntered

    private void logButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseExited
        logButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_logButtonMouseExited

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        dispose();
        new Register();
    }//GEN-LAST:event_registerButtonMouseClicked

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
        registerButton.setBackground(Color.GRAY);
        registerButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_registerButtonMouseEntered

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseExited
        registerButton.setBackground(Color.WHITE);
        registerButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerButtonMouseExited

    private void loginFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFinishActionPerformed

    private void loginFinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFinishMouseExited
        loginFinish.setForeground(Color.BLACK);
    }//GEN-LAST:event_loginFinishMouseExited

    private void loginFinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFinishMouseEntered
        loginFinish.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginFinishMouseEntered

    private void loginFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFinishMouseClicked
                String getUsername = username.getText();
                String getPass = new String(password.getPassword());
                String getBoth = getUsername+","+getPass;
                File file = new File("src/main/data/user.csv");
                if (!file.exists()) {
                    System.out.println("User file not found!");
                    return; // หยุดการทำงานถ้าไฟล์ไม่เจอ
                }
                boolean loginSuccess = false; // ตัวแปรเก็บสถานะ login
                try (BufferedReader br = new BufferedReader(
                    new InputStreamReader(new FileInputStream(file), "UTF-8"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        if (!line.trim().isEmpty()) {
                            String[] parts = line.split(","); // userID,username,password,tel
                            if (parts.length >= 3) {
                                String fileUsername = parts[1];
                                String filePassword = parts[2];
                                String confirmlogin = (fileUsername+","+filePassword);
                                if (getBoth.equals(confirmlogin)) {
                                    loginSuccess = true; // login สำเร็จ
                                    break; // เจอแล้วก็หยุด loop
                                
                                }
                            }
                        }
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
                // ตรวจสอบผลลัพธ์ login
                if (loginSuccess) {
                    cautionusername.setVisible(false);
                    cautionpass.setVisible(false);
                    password.setText(""); 
                    dispose();
                    new HomePage();
                    //new BookingPage(getUsername);
                } else {
                    cautionusername.setText("U R Username not equal in database just register");
                    cautionpass.setText("U R Password not equal in database just input true password");
                    cautionusername.setVisible(true); // แสดงข้อความผิดพลาด
                    cautionpass.setVisible(true);
                    password.setText(""); // ล้าง password
                    System.out.println("false");
                }
    }//GEN-LAST:event_loginFinishMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        
    }//GEN-LAST:event_usernameKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anotherRegister;
    private javax.swing.JLabel cautionpass;
    private javax.swing.JLabel cautionusername;
    private javax.swing.JLabel iconpassword;
    private javax.swing.JLabel iconusername;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logButton;
    private javax.swing.JButton loginFinish;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
