/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.*;
import java.util.*;
import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;
/**
 *
 * @author User
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    private String user;
    private String Tell;
    private String experience;
    private String currentUserName = "";
    
    
    /**
     * Creates new form Profile
     */
    public Profile() {
        
        initComponents();
        setupui();
        /*homebutton.putClientProperty("JButton.buttonType", "roundRect");
        homebutton.putClientProperty("arc",5);
        historybutton.putClientProperty("JButton.buttonType", "roundRect");
        historybutton.putClientProperty("arc",5);
        bookingbutton.putClientProperty("JButton.buttonType", "roundRect");
        bookingbutton.putClientProperty("arc", 5);*/
         setSize(1280, 800);  
         setLocationRelativeTo(null); // จัดตรงกลางจอ
         setVisible(true);
         loadFromCSV();
         loadUserProfile(currentUserName);
    }
    private void setupui(){
        homebutton.setBorderPainted(false);
        historybutton.setBorderPainted(false);
        bookingbutton.setBorderPainted(false);
        profilebutton.setBorderPainted(false);
    }
    private void loadFromCSV() {
    String filePath = "src/main/data/user.csv"; // ตำแหน่งไฟล์
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        boolean isFirstLine = true;
        while ((line = br.readLine()) != null) {
            if (isFirstLine) { 
                isFirstLine = false; // ข้ามบรรทัด header
                continue;
            }

            String[] values = line.split(",");

            // สมมติเลือกบรรทัดแรกสุด
            if (values.length >= 4) {
                usernameText.setText(values[1]);       // Name
                tellText.setText(values[3]);       // Phone
                experienceText.setText(values[2]); // Email (หรือเปลี่ยนเป็น exp ถ้ามี)
            }
            break; // โหลดแค่แถวแรกพอ
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    
}
private void updateFirstRowCSV(String newName, String newEmail, String newPhone) {
    String filePath = "src/main/data/user.csv"; // ที่อยู่ไฟล์ CSV
    List<String> lines = new ArrayList<>();          // เก็บข้อมูลแต่ละบรรทัด

    // อ่านไฟล์ CSV ทั้งหมดเก็บใน list
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        while ((line = br.readLine()) != null) lines.add(line);
    } catch (IOException e) { e.printStackTrace(); }

    // ✅ ถ้ามีข้อมูลมากกว่า 1 บรรทัด (มี header + อย่างน้อย 1 record)
    if (lines.size() > 1) {
        // แก้เฉพาะบรรทัดแรก (index 1) โดยใส่ค่าที่พิมพ์จากฟอร์ม
        lines.set(1, "1," + newName + "," + newEmail + "," + newPhone);
    }

    // เขียน list ทั้งหมดกลับไปที่ไฟล์ (แทนที่ของเก่า)
    try (PrintWriter pw = new PrintWriter(new FileWriter(filePath))) {
        for (String l : lines) pw.println(l); // วนเขียนแต่ละบรรทัด
    } catch (IOException e) { e.printStackTrace(); }
}
private void loadUserProfile(String name) {
    //userlabel.setLabel("" + currentUserName);
    String filePath = "src/main/data/user.csv";
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        boolean isFirstLine = true;

        while ((line = br.readLine()) != null) {
            if (isFirstLine) {
                isFirstLine = false; // ข้าม header
                continue;
            }

            String[] values = line.split(",");
            if (values[1].trim().equals(name)) {
                usernameText.setText(values[1]);   // Name
                tellText.setText(values[3]);       // Phone
                experienceText.setText(values[2]); // Email
                break;
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        texttInbtnHome = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        texttInbtnHistory = new javax.swing.JLabel();
        historybutton = new javax.swing.JButton();
        texttInbtnBooking = new javax.swing.JLabel();
        bookingbutton = new javax.swing.JButton();
        texttInbtnProfile = new javax.swing.JLabel();
        profilebutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usernameText = new javax.swing.JTextField();
        tellText = new javax.swing.JTextField();
        experienceText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texttInbtnEdittext = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 58, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 110, 40));

        userlabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 200, 40));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 104));

        jPanel2.setBackground(new java.awt.Color(28, 24, 24));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texttInbtnHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnHome.setForeground(new java.awt.Color(255, 255, 255));
        texttInbtnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnHome.setText("Home");
        texttInbtnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        texttInbtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnHomeMouseClicked(evt);
            }
        });
        jPanel2.add(texttInbtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        homebutton.setBackground(new java.awt.Color(28, 24, 24));
        homebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebuttonMouseExited(evt);
            }
        });
        jPanel2.add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 164, 90));

        texttInbtnHistory.setBackground(new java.awt.Color(255, 255, 255));
        texttInbtnHistory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnHistory.setForeground(new java.awt.Color(255, 255, 255));
        texttInbtnHistory.setText("History");
        texttInbtnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnHistoryMouseClicked(evt);
            }
        });
        jPanel2.add(texttInbtnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        historybutton.setBackground(new java.awt.Color(28, 24, 24));
        historybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historybuttonMouseExited(evt);
            }
        });
        jPanel2.add(historybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 164, 90));

        texttInbtnBooking.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnBooking.setForeground(new java.awt.Color(255, 255, 255));
        texttInbtnBooking.setText("Booking");
        texttInbtnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnBookingMouseClicked(evt);
            }
        });
        jPanel2.add(texttInbtnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        bookingbutton.setBackground(new java.awt.Color(28, 24, 24));
        bookingbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bookingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingbuttonMouseExited(evt);
            }
        });
        bookingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(bookingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 164, 90));

        texttInbtnProfile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnProfile.setText("Profile");
        texttInbtnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnProfileMouseClicked(evt);
            }
        });
        jPanel2.add(texttInbtnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, -1, -1));

        profilebutton.setBackground(new java.awt.Color(255, 149, 0));
        jPanel2.add(profilebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 164, 90));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 225, 800));

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameText.setBackground(new java.awt.Color(217, 217, 217));
        usernameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameText.setActionCommand("<Not Set>");
        usernameText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 646, 63));

        tellText.setBackground(new java.awt.Color(217, 217, 217));
        tellText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tellText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(tellText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 646, 63));

        experienceText.setBackground(new java.awt.Color(217, 217, 217));
        experienceText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        experienceText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        experienceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experienceTextActionPerformed(evt);
            }
        });
        jPanel4.add(experienceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 646, 63));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tell :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("experience :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        texttInbtnEdittext.setBackground(new java.awt.Color(0, 0, 0));
        texttInbtnEdittext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnEdittext.setForeground(new java.awt.Color(255, 255, 255));
        texttInbtnEdittext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnEdittext.setText("Save");
        texttInbtnEdittext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnEdittextMouseClicked(evt);
            }
        });
        jPanel4.add(texttInbtnEdittext, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 110, 71));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 871, 545));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 911, 583));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void experienceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experienceTextActionPerformed
        

    }//GEN-LAST:event_experienceTextActionPerformed

    private void texttInbtnEdittextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnEdittextMouseClicked
        user = usernameText.getText();
            System.out.println("User : "+ user);
        Tell = tellText.getText();
            System.out.println("Tell : "+ Tell);     
        experience = experienceText.getText();
            System.out.println("experience : "+ experience);
            updateFirstRowCSV(
        usernameText.getText(),       // Name
        experienceText.getText(), // Email
        tellText.getText()        // Phone 
        );
    }//GEN-LAST:event_texttInbtnEdittextMouseClicked

    private void texttInbtnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnProfileMouseClicked

    private void texttInbtnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnHistoryMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnHistoryMouseClicked

    private void texttInbtnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnBookingMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnBookingMouseClicked

    private void texttInbtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnHomeMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnHomeMouseClicked

    private void homebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseEntered
        homebutton.setBackground(Color.GRAY);
        texttInbtnHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_homebuttonMouseEntered

    private void homebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebuttonMouseExited
       homebutton.setBackground(new Color(28,24,24));
       texttInbtnHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_homebuttonMouseExited

    private void historybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseEntered
        historybutton.setBackground(Color.GRAY);
        texttInbtnHistory.setForeground(Color.WHITE);
    }//GEN-LAST:event_historybuttonMouseEntered

    private void historybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseExited
        historybutton.setBackground(new Color(28,24,24));
        texttInbtnHistory.setForeground(Color.WHITE);
    }//GEN-LAST:event_historybuttonMouseExited

    private void bookingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbuttonActionPerformed

    private void bookingbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingbuttonMouseEntered
        bookingbutton.setBackground(Color.GRAY);
        texttInbtnBooking.setForeground(Color.WHITE);
    }//GEN-LAST:event_bookingbuttonMouseEntered

    private void bookingbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingbuttonMouseExited
        bookingbutton.setBackground(new Color(28,24,24));
        texttInbtnBooking.setForeground(Color.WHITE);
    }//GEN-LAST:event_bookingbuttonMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField experienceText;
    private javax.swing.JButton historybutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton profilebutton;
    private javax.swing.JTextField tellText;
    private javax.swing.JLabel texttInbtnBooking;
    private javax.swing.JLabel texttInbtnEdittext;
    private javax.swing.JLabel texttInbtnHistory;
    private javax.swing.JLabel texttInbtnHome;
    private javax.swing.JLabel texttInbtnProfile;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
