/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author usEr
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
            setSize(1200, 800);  
            setLocationRelativeTo(null);
            setVisible(true);
            cautionusername.setVisible(false); 
            cautionpass.setVisible(false); 
            cautionconfirmpass.setVisible(false); 
            cautiontel.setVisible(false); 
            iconusername.setIcon(new ImageIcon(getClass().getResource("/image/user.png")));
            iconpassword.setIcon(new ImageIcon(getClass().getResource("/image/padlock.png")));
            iconconfirmpassword.setIcon(new ImageIcon(getClass().getResource("/image/padlock.png")));
            icontel.setIcon(new ImageIcon(getClass().getResource("/image/phone-call.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logButton = new javax.swing.JButton();
        cautionusername = new javax.swing.JLabel();
        cautionpass = new javax.swing.JLabel();
        cautionconfirmpass = new javax.swing.JLabel();
        cautiontel = new javax.swing.JLabel();
        iconusername = new javax.swing.JLabel();
        iconpassword = new javax.swing.JLabel();
        iconconfirmpassword = new javax.swing.JLabel();
        icontel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextTel = new javax.swing.JTextField();
        registerFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(58, 58, 58));

        registerButton.setBackground(new java.awt.Color(255, 149, 0));
        registerButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jLabel2.setToolTipText("");

        logButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        logButton.setText("Login");
        logButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logButtonMouseExited(evt);
            }
        });
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 800));

        cautionusername.setForeground(new java.awt.Color(255, 0, 0));
        cautionusername.setText("Passwords don't match !!! please try again");
        cautionusername.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(cautionusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, -1));

        cautionpass.setForeground(new java.awt.Color(255, 0, 0));
        cautionpass.setText("Passwords don't match !!! please try again");
        cautionpass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(cautionpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        cautionconfirmpass.setForeground(new java.awt.Color(255, 0, 0));
        cautionconfirmpass.setText("Passwords don't match !!! please try again");
        cautionconfirmpass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(cautionconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        cautiontel.setForeground(new java.awt.Color(255, 0, 0));
        cautiontel.setText("Passwords don't match !!! please try again");
        cautiontel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(cautiontel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));
        jPanel1.add(iconusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 50, 60));
        jPanel1.add(iconpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 50, 60));
        jPanel1.add(iconconfirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 50, 60));
        jPanel1.add(icontel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 50, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, 62));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        username.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        username.setMargin(new java.awt.Insets(2, 55, 2, 6));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 510, 60));

        password.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        password.setMargin(new java.awt.Insets(2, 55, 2, 6));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 510, 60));

        confirmPassword.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        confirmPassword.setMargin(new java.awt.Insets(2, 55, 2, 6));
        confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 420, 510, 60));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tel   000-000-0000");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jTextTel.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jTextTel.setMargin(new java.awt.Insets(2, 55, 2, 6));
        jTextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelActionPerformed(evt);
            }
        });
        jTextTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelKeyTyped(evt);
            }
        });
        jPanel1.add(jTextTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 530, 510, 60));

        registerFinish.setBackground(new java.awt.Color(255, 149, 0));
        registerFinish.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        registerFinish.setText("Register");
        registerFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerFinishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerFinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerFinishMouseExited(evt);
            }
        });
        registerFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFinishActionPerformed(evt);
            }
        });
        jPanel1.add(registerFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 510, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordActionPerformed

    private void jTextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelActionPerformed

    private void jTextTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (jTextTel.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextTelKeyTyped

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        dispose();
        new Register();
    }//GEN-LAST:event_registerButtonMouseClicked

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
        
        registerButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_registerButtonMouseEntered

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseExited
        
        registerButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerButtonMouseExited

    private void logButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseClicked
        dispose();
        new Login();
    }//GEN-LAST:event_logButtonMouseClicked

    private void logButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseEntered
        logButton.setBackground(Color.GRAY);
        logButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_logButtonMouseEntered

    private void logButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButtonMouseExited
        logButton.setBackground(Color.WHITE);
        logButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_logButtonMouseExited

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logButtonActionPerformed

    private void registerFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerFinishMouseClicked
        String pass = new String(password.getPassword());
        int sumuser = 0;
        int sumpass = 0;
        int sumconfirm = 0;
        int sumtel = 0;
            if (pass.isEmpty()) {
                cautionusername.setText("Need to input username");
                cautionusername.setVisible(true);
                sumuser=1;
            }else{
                cautionusername.setVisible(false);
                sumuser=0;
            }
            if (pass.isEmpty()) {
                cautionpass.setText("Need to input password");
                cautionpass.setVisible(true);
                sumpass=1;
            }else{
                cautionpass.setVisible(false);
                sumpass=0;
            }
            if (pass.isEmpty()) {
                cautionconfirmpass.setText("Need to confirm password");
                cautionconfirmpass.setVisible(true);
                sumconfirm=1;
            }else{
                cautionconfirmpass.setVisible(false);
                sumconfirm=0;
            }
            if (pass.isEmpty()) {
                cautiontel.setText("Need to input your tel");
                cautiontel.setVisible(true);
                sumtel=1;
            }else{
                cautiontel.setVisible(false);
                sumtel=0;
            }
            /*
            if (pass.length() < 8) {
                cautionusername.setText("Password need at least 8 characters");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }
            if (pass.contains(" ")) {
                cautionusername.setText("Password must not contain spaces");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }

            if (!pass.matches(".*\\d.*")) {
                cautionusername.setText("Password must have at least one number");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }

            if (!pass.matches(".*[a-z].*")) {
                cautionusername.setText("Password must have at least one lowercase letter");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }

            if (!pass.matches(".*[A-Z].*")) {
                cautionusername.setText("Password must have at least one uppercase letter");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }

            if (!pass.matches(".*[!@#$%^&*()].*")) {
                cautionusername.setText("Password must have at least one special character (!@#$%^&*())");
                cautionusername.setVisible(true);
                sumpass=1;
            }else{
                sumpass=0;
            }
            */

            if (sumpass != 1&& sumuser != 1&&sumconfirm!=1&&sumtel != 1){
                cautionusername.setVisible(false); 
                cautionpass.setVisible(false); 
                cautionconfirmpass.setVisible(false); 
                cautiontel.setVisible(false); 
                password.setText(""); 
                System.out.print(username.getText() + "\n" + pass);
                dispose();
            }
    }//GEN-LAST:event_registerFinishMouseClicked

    private void registerFinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerFinishMouseEntered
        registerFinish.setForeground(Color.WHITE);
    }//GEN-LAST:event_registerFinishMouseEntered

    private void registerFinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerFinishMouseExited
        registerFinish.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerFinishMouseExited

    private void registerFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cautionconfirmpass;
    private javax.swing.JLabel cautionpass;
    private javax.swing.JLabel cautiontel;
    private javax.swing.JLabel cautionusername;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel iconconfirmpassword;
    private javax.swing.JLabel iconpassword;
    private javax.swing.JLabel icontel;
    private javax.swing.JLabel iconusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextTel;
    private javax.swing.JButton logButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerFinish;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
