/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carservice.gui;

import java.awt.Color;

/**
 *
 * @author User
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    private String user;
    private String Tell;
    private String experience;
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
         setSize(1280, 800);  
         setLocationRelativeTo(null); // จัดตรงกลางจอ
         setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        texttInbtnHome = new javax.swing.JLabel();
        booking = new javax.swing.JPanel();
        texttInbtnBooking = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        texttInbtnHistory = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        texttInbtnProfile = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usernameText = new javax.swing.JTextField();
        tellText = new javax.swing.JTextField();
        experienceText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edittext = new javax.swing.JPanel();
        texttInbtnEdittext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 58, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 110, 40));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 104));

        jPanel2.setBackground(new java.awt.Color(28, 24, 24));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        texttInbtnHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnHome.setText("Home");
        texttInbtnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        texttInbtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(texttInbtnHome)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(texttInbtnHome)
                .addGap(26, 26, 26))
        );

        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 164, 90));

        booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingMouseExited(evt);
            }
        });

        texttInbtnBooking.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnBooking.setText("Booking");
        texttInbtnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnBookingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bookingLayout = new javax.swing.GroupLayout(booking);
        booking.setLayout(bookingLayout);
        bookingLayout.setHorizontalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(texttInbtnBooking)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        bookingLayout.setVerticalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(texttInbtnBooking)
                .addGap(26, 26, 26))
        );

        jPanel2.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 164, 90));

        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historyMouseExited(evt);
            }
        });

        texttInbtnHistory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnHistory.setText("History");
        texttInbtnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnHistoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout historyLayout = new javax.swing.GroupLayout(history);
        history.setLayout(historyLayout);
        historyLayout.setHorizontalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(texttInbtnHistory)
                .addGap(42, 42, 42))
        );
        historyLayout.setVerticalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(texttInbtnHistory)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 164, 90));

        jPanel9.setBackground(new java.awt.Color(255, 157, 0));

        texttInbtnProfile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnProfile.setText("Profile");
        texttInbtnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(texttInbtnProfile)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(texttInbtnProfile)
                .addGap(26, 26, 26))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 164, 90));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 225, 800));

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameText.setBackground(new java.awt.Color(217, 217, 217));
        usernameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameText.setActionCommand("<Not Set>");
        usernameText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 646, 63));

        tellText.setBackground(new java.awt.Color(217, 217, 217));
        tellText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tellText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel4.add(tellText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 646, 63));

        experienceText.setBackground(new java.awt.Color(217, 217, 217));
        experienceText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        experienceText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        experienceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experienceTextActionPerformed(evt);
            }
        });
        jPanel4.add(experienceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 646, 63));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tell :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("experience :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        edittext.setBackground(new java.awt.Color(0, 0, 0));
        edittext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edittextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edittextMouseExited(evt);
            }
        });

        texttInbtnEdittext.setBackground(new java.awt.Color(0, 0, 0));
        texttInbtnEdittext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texttInbtnEdittext.setForeground(new java.awt.Color(255, 255, 255));
        texttInbtnEdittext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texttInbtnEdittext.setText("Save");
        texttInbtnEdittext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texttInbtnEdittextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edittextLayout = new javax.swing.GroupLayout(edittext);
        edittext.setLayout(edittextLayout);
        edittextLayout.setHorizontalGroup(
            edittextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edittextLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(texttInbtnEdittext)
                .addGap(28, 28, 28))
        );
        edittextLayout.setVerticalGroup(
            edittextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edittextLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(texttInbtnEdittext)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.add(edittext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 110, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 871, 545));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 911, 583));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void experienceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experienceTextActionPerformed
        

    }//GEN-LAST:event_experienceTextActionPerformed

    private void texttInbtnEdittextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnEdittextMouseClicked
        user = usernameText.getText();
            System.out.println("User : "+ user);
        Tell = tellText.getText();
            System.out.println("Tell : "+ Tell);     
        experience = experienceText.getText();
            System.out.println("experience : "+ experience);
    }//GEN-LAST:event_texttInbtnEdittextMouseClicked

    private void texttInbtnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnProfileMouseClicked

    private void texttInbtnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnHistoryMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnHistoryMouseClicked

    private void texttInbtnBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnBookingMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnBookingMouseClicked

    private void texttInbtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texttInbtnHomeMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_texttInbtnHomeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(Color.GRAY);
       texttInbtnHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(Color.WHITE);
         texttInbtnHome.setForeground(Color.BLACK);
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
       
    }//GEN-LAST:event_homeMouseClicked

    private void bookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseEntered
         booking.setBackground(Color.GRAY);
         texttInbtnBooking.setForeground(Color.WHITE);
    }//GEN-LAST:event_bookingMouseEntered

    private void bookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseExited
        booking.setBackground(Color.WHITE);
         texttInbtnBooking.setForeground(Color.BLACK);
    }//GEN-LAST:event_bookingMouseExited

    private void historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseEntered
      history.setBackground(Color.GRAY);
         texttInbtnHistory.setForeground(Color.WHITE);                                   
    }//GEN-LAST:event_historyMouseEntered

    private void historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseExited
        history.setBackground(Color.WHITE);
         texttInbtnHistory.setForeground(Color.BLACK); 
    }//GEN-LAST:event_historyMouseExited

    private void edittextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittextMouseEntered
        edittext.setBackground(Color.GRAY);
         texttInbtnEdittext.setForeground(Color.BLACK);  
    }//GEN-LAST:event_edittextMouseEntered

    private void edittextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittextMouseExited
        edittext.setBackground(Color.BLACK  );
         texttInbtnEdittext.setForeground(Color.WHITE);  
    }//GEN-LAST:event_edittextMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booking;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel edittext;
    private javax.swing.JTextField experienceText;
    private javax.swing.JPanel history;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField tellText;
    private javax.swing.JLabel texttInbtnBooking;
    private javax.swing.JLabel texttInbtnEdittext;
    private javax.swing.JLabel texttInbtnHistory;
    private javax.swing.JLabel texttInbtnHome;
    private javax.swing.JLabel texttInbtnProfile;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
